name: Format Check

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  format-check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dotnet-format
        run: |
          dotnet tool install -g dotnet-format --version 6.* || true
          export PATH="$PATH:$HOME/.dotnet/tools"

      - name: Run dotnet format (check)
        run: |
          dotnet format --verify-no-changes
        shell: powershell
